SELECT NAME, OPEN_MODE, RESTRICTED FROM V$PDBS;
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE "DADOS"
DATAFILE 'C:\app\vinic\product\21c\database\datafile2.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;

ALTER DATABASE DEFAULT TABLESPACE "DADOS";

SHOW TABLESPACES;