SELECT NAME, OPEN_MODE, RESTRICTED FROM V$PDBS;
ALTER SESSION SET CONTAINER = XEPDB1;

SHOW PARAMETER COMMON_USER_PREFIX;

CREATE USER exemplo01 profile "DEFAULT" identified by "123"
DEFAULT TABLESPACE "DADOS"
QUOTA UNLIMITED ON "DADOS"
ACCOUNT UNLOCK;

GRANT CONNECT TO exemplo01;
GRANT CREATE TABLE TO exemplo01;
GRANT CREATE PROCEDURE TO exemplo01;
GRANT CREATE TRIGGER TO exemplo01;
GRANT CREATE VIEW TO exemplo01;
GRANT CREATE SEQUENCE TO exemplo01;
GRANT CREATE JOB TO exemplo01;